#!/usr/bin/env python3
"""Convert dhepper/font8x8 `*.h` C headers into Rust const byte
arrays in `../src/fonts/`. Run from the crate root:

    python3 tools/gen_fonts.py

Parses the `char font8x8_<name>[N][8] = { { 0xHH, ... }, ... };`
form and emits a matching `FONT8X8_<NAME>: [u8; N*8]` const plus
a `BitmapFont` descriptor set up to reference it. The generator
is separate from `build.rs` so generated Rust lands in source
control — readable diffs when fonts change, no build-script
dependency on Python.

Kept pure-Python3 stdlib so contributors don't need extra tooling.
"""

import re
import sys
from pathlib import Path

CRATE_ROOT = Path(__file__).resolve().parent.parent
VENDOR = CRATE_ROOT / "vendor"
OUT = CRATE_ROOT / "src" / "fonts"

HEADER_BLOCK = '''// This file is GENERATED by `tools/gen_fonts.py` from
// `vendor/{source_name}`. Do NOT edit by hand — re-run the
// generator if the upstream font source changes.
//
// License: Public Domain (see `vendor/PROVENANCE.md`).

use crate::{{BitOrder, BitmapFont}};

'''

# Each entry:  (header_file, const_name, first_codepoint, glyph_count, doc)
#
# `first_codepoint` is the ASCII/Unicode code of glyph 0 in the
# bitmap array. dhepper's `basic` starts at U+0000 with the first
# printable glyph at U+0020 — our `BitmapFont` carries first_char
# so we can slice the array to just the printable range at upload
# time, saving VRAM.
FONTS = [
    ("font8x8_basic.h", "basic", "BASIC",
     0x00, 128,
     "ASCII 0x00..0x7F — the printable range (0x20..0x7E) is the\n"
     "  default for English + C-source text. Control-character\n"
     "  glyphs (0x00..0x1F) are empty in dhepper's basic; use\n"
     "  `font8x8_control` if you need visible control glyphs."),
    ("font8x8_ext_latin.h", "ext_latin", "EXT_LATIN",
     0xA0, 96,
     "Latin-1 supplement, U+00A0..U+00FF (96 glyphs). Accented\n"
     "  letters + currency + punctuation for Western European\n"
     "  languages. dhepper's upstream calls this file `ext_latin`\n"
     "  even though its codepoint range is the Latin-1 supplement.\n"
     "  Pair with `BASIC` for a full Latin-1-capable atlas."),
    ("font8x8_box.h", "boxdraw", "BOXDRAW",
     0x2500, 128,
     "Box-drawing U+2500..U+257F — single/double line corners and\n"
     "  intersections. Handy for framing menus. (`box` is a reserved\n"
     "  keyword in Rust, so the module is named `boxdraw`.)"),
]


def parse_font_file(path: Path, expected_glyphs: int) -> list[list[int]]:
    text = path.read_text()
    # Each glyph line looks like:
    #   { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},   // U+0000 (nul)
    glyph_re = re.compile(
        r"\{\s*(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*,\s*"
        r"(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*,\s*"
        r"(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*,\s*"
        r"(0x[0-9a-fA-F]{2})\s*,\s*(0x[0-9a-fA-F]{2})\s*\}"
    )
    glyphs = []
    for match in glyph_re.finditer(text):
        row_bytes = [int(g, 16) for g in match.groups()]
        glyphs.append(row_bytes)
    if len(glyphs) != expected_glyphs:
        raise SystemExit(
            f"{path.name}: parsed {len(glyphs)} glyphs, expected {expected_glyphs}"
        )
    return glyphs


def emit_font_module(
    source: str, mod: str, const_prefix: str,
    first_cp: int, count: int, doc: str, glyphs: list[list[int]],
) -> str:
    buf = [HEADER_BLOCK.format(source_name=source)]
    for line in doc.strip().split("\n"):
        line = line.lstrip()
        if line:
            buf.append(f"/// {line}\n")
        else:
            buf.append("///\n")
    buf.append(f"///\n")
    buf.append(f"/// 8×8 pixels per glyph, 1 bit per pixel, LSB = leftmost.\n")
    buf.append(
        f"pub const {const_prefix}_BITMAP: [u8; {count * 8}] = [\n"
    )
    for i, rows in enumerate(glyphs):
        cp = first_cp + i
        hex_row = ", ".join(f"0x{b:02x}" for b in rows)
        comment = f"U+{cp:04X}"
        if 0x20 <= cp <= 0x7E:
            comment += f" ({chr(cp)!r})"
        buf.append(f"    {hex_row}, // {comment}\n")
    buf.append("];\n\n")
    buf.append(
        f"/// [`BitmapFont`] descriptor for the `{mod}` bitmap above.\n"
        f"/// Pass into [`crate::FontAtlas::upload`] to install it in VRAM.\n"
        f"pub const {const_prefix}: BitmapFont = BitmapFont {{\n"
        f"    glyph_w: 8,\n"
        f"    glyph_h: 8,\n"
        f"    first_char: 0x{first_cp:04x},\n"
        f"    glyph_count: {count},\n"
        f"    bitmap: &{const_prefix}_BITMAP,\n"
        f"    advance_x: 8,\n"
        f"    line_height: 8,\n"
        f"    bit_order: BitOrder::Lsb,\n"
        f"}};\n"
    )
    return "".join(buf)


def main() -> None:
    if not VENDOR.is_dir():
        raise SystemExit(f"missing vendor dir {VENDOR}")
    OUT.mkdir(parents=True, exist_ok=True)
    mod_lines = [
        "//! Built-in fonts — all Public Domain (dhepper/font8x8).\n",
        "//!\n",
        "//! Generated by `tools/gen_fonts.py`. Add new entries there\n",
        "//! rather than editing this file by hand.\n",
        "\n",
    ]
    for source, mod, const_prefix, first_cp, count, doc in FONTS:
        glyphs = parse_font_file(VENDOR / source, count)
        out_path = OUT / f"{mod}.rs"
        out_path.write_text(emit_font_module(
            source, mod, const_prefix, first_cp, count, doc, glyphs,
        ))
        print(f"wrote {out_path.relative_to(CRATE_ROOT)} — {count} glyphs")
        mod_lines.append(
            f"/// Built-in font: `{mod}` "
            f"(U+{first_cp:04X}..U+{first_cp + count - 1:04X}, "
            f"{count} glyphs).\n"
        )
        mod_lines.append(f"pub mod {mod};\n")
    mod_lines.append("\n")
    mod_lines.append("// Flat re-exports so call sites read as\n")
    mod_lines.append("// `psx_font::fonts::BASIC` etc.\n")
    for _, mod, const_prefix, _, _, _ in FONTS:
        mod_lines.append(f"pub use {mod}::{const_prefix};\n")
    (OUT / "mod.rs").write_text("".join(mod_lines))
    print(f"wrote {(OUT / 'mod.rs').relative_to(CRATE_ROOT)}")


if __name__ == "__main__":
    main()
