#!/usr/bin/env python3
"""Generate pre-baked PSX ADPCM tone samples for `psx-spu`.

Emits raw 16-byte ADPCM blocks matching PSX-SPX's "SPU ADPCM Samples
(PS1)" section. Each tone is a single 16-byte block with both loop-
start and loop-end flags set — the SPU restarts playback from the
same block continuously, giving a sustained tone at a frequency
determined by the playback pitch.

Run from `sdk/crates/psx-spu/`:

    python3 tools/gen_tones.py

Writes `vendor/*.adpcm` (raw bytes) and `src/tones.rs` (Rust const
arrays referencing the vendored bytes via `include_bytes!`).

Block layout recap:
  byte 0: `(shift << 0) | (filter << 4)`  — shift 0..12, filter 0..4
  byte 1: flags  — bit 0 = loop end, bit 1 = repeat, bit 2 = loop start
  bytes 2..15: 14 bytes = 28 4-bit signed nibbles (low nibble first)
"""

import math
import struct
from pathlib import Path

CRATE_ROOT = Path(__file__).resolve().parent.parent
VENDOR = CRATE_ROOT / "vendor"
OUT = CRATE_ROOT / "src" / "tones.rs"

# Single-block tones: each is a 28-sample waveform that the SPU
# loops indefinitely. Playback frequency = 44100 / 28 × (pitch /
# 0x1000). A native-rate play of a 28-sample cycle gives ~1575 Hz.
TONES = [
    ("SINE", "Pure sine wave. Smooth, tonal — the default tuning reference."),
    ("SQUARE", "Hard square wave. Buzzier, classic 8-bit timbre."),
    ("TRIANGLE", "Triangle wave. Softer than square, richer than sine."),
    ("SAWTOOTH", "Sawtooth ramp. Bright, full-spectrum — good for chiptune leads."),
]


def make_sine_samples() -> list[int]:
    """28 samples of one full sine period, quantised to 4-bit signed."""
    return [
        max(-8, min(7, round(math.sin(2 * math.pi * i / 28) * 7)))
        for i in range(28)
    ]


def make_square_samples() -> list[int]:
    """28 samples of a 50% duty square, clipped to ±7."""
    return [7 if i < 14 else -7 for i in range(28)]


def make_triangle_samples() -> list[int]:
    """28 samples of a triangle — up for 14, down for 14."""
    out = []
    for i in range(28):
        if i < 14:
            # 0..13 mapping onto -7..+7
            out.append(-7 + round(14 * i / 13))
        else:
            # 14..27 mapping onto +7..-7
            out.append(7 - round(14 * (i - 14) / 13))
    # Clamp in case rounding pushes past ±7.
    return [max(-7, min(7, v)) for v in out]


def make_sawtooth_samples() -> list[int]:
    """28 samples of a sawtooth ramp, -7..+7."""
    return [max(-7, min(7, -7 + round(14 * i / 27))) for i in range(28)]


def encode_block(samples: list[int], shift: int = 8, filter_: int = 0,
                 flags: int = 0x07) -> bytes:
    """Encode 28 nibble samples as a 16-byte PSX ADPCM block.

    Default flags=0x07 mark this block as a self-contained loop:
    bit 0 (loop end) + bit 1 (repeat) + bit 2 (loop start) set
    together mean "SPU restarts from this block's address when it
    finishes playing it" — so the voice sustains the tone until
    key-off.

    `shift` picks the decoded amplitude. shift=8 with 4-bit nibbles
    in ±7 gives final samples in ±1792 — audible but not clipped.
    """
    assert 0 <= shift <= 12
    assert 0 <= filter_ <= 4
    assert len(samples) == 28
    header = bytes([(shift & 0x0F) | ((filter_ & 0x0F) << 4), flags & 0xFF])
    body = bytearray(14)
    for i, s in enumerate(samples):
        nibble = s & 0x0F
        byte_idx = i // 2
        if i % 2 == 0:
            body[byte_idx] |= nibble
        else:
            body[byte_idx] |= nibble << 4
    return header + bytes(body)


GENERATORS = {
    "SINE": make_sine_samples,
    "SQUARE": make_square_samples,
    "TRIANGLE": make_triangle_samples,
    "SAWTOOTH": make_sawtooth_samples,
}


HEADER_BLOCK = '''//! Built-in ADPCM tone samples.
//!
//! Each tone is a single 16-byte ADPCM block with self-loop flags
//! set (0x07 = loop end + repeat + loop start), so the SPU
//! sustains the waveform until [`crate::Voice::key_off`]. Native
//! playback frequency at [`crate::Pitch::UNITY`] is ~1575 Hz
//! (44100 / 28 samples per loop); use [`crate::Pitch::for_frequency`]
//! to tune to a specific note.
//!
//! Generated by `tools/gen_tones.py` from hand-rolled waveform
//! definitions — no external dependency on an ADPCM encoder.

'''


def main() -> None:
    VENDOR.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)

    buf = [HEADER_BLOCK]
    buf.append(
        "/// Native playback frequency (Hz) when a single-block\n"
        "/// tone is played at [`crate::Pitch::UNITY`]. The 28-sample\n"
        "/// loop at 44100 Hz gives 44100 / 28 = 1575 Hz.\n"
        "pub const NATIVE_HZ: u32 = 1575;\n\n"
    )
    for name, doc in TONES:
        samples = GENERATORS[name]()
        block = encode_block(samples)
        path = VENDOR / f"tone_{name.lower()}.adpcm"
        path.write_bytes(block)
        print(f"wrote {path.relative_to(CRATE_ROOT)} — {len(block)} bytes")
        # Embed via include_bytes! so the generated Rust stays tiny
        # and the vendored file carries the authoritative bytes.
        rel = f"../vendor/tone_{name.lower()}.adpcm"
        buf.append(f"/// {doc}\n")
        buf.append(
            f'pub const {name}: &[u8; 16] = include_bytes!("{rel}");\n\n'
        )
    OUT.write_text("".join(buf))
    print(f"wrote {OUT.relative_to(CRATE_ROOT)}")


if __name__ == "__main__":
    main()
