//! Built-in fonts — all Public Domain (dhepper/font8x8).
//!
//! Generated by `tools/gen_fonts.py`. Add new entries there
//! rather than editing this file by hand.

/// Built-in font: `basic` (U+0000..U+007F, 128 glyphs).
pub mod basic;
/// Built-in font: `ext_latin` (U+00A0..U+00FF, 96 glyphs).
pub mod ext_latin;
/// Built-in font: `boxdraw` (U+2500..U+257F, 128 glyphs).
pub mod boxdraw;

// Flat re-exports so call sites read as
// `psx_font::fonts::BASIC` etc.
pub use basic::BASIC;
pub use ext_latin::EXT_LATIN;
pub use boxdraw::BOXDRAW;
